function change_language(){
  var dataReload=document.querySelectorAll("[data-reload]");
  let language={
    eng:{
      letter_1:"H",letter_2:"e",letter_3:"l",letter_4:"l",letter_5:"o",
      letter_6:"!",letter_7:"M",letter_8:"",letter_9:"y",letter_10:"n",
      letter_11:"a",letter_12:"m",letter_13:"e",letter_14:"i",letter_15:"",
      letter_16:"",letter_17:"s",letter_18:"P",letter_19:"a",letter_20:"t",
      letter_21:"r",letter_22:"y",letter_23:"k",letter_24:",",letter_25:"I",
      letter_26:"'",letter_27:"",letter_28:"",letter_29:"",letter_30:"m",
      letter_31:"f",letter_32:"r",letter_33:"e",letter_34:"e",letter_35:"l",
      letter_36:"a",letter_37:"n",letter_38:"c",letter_39:"",letter_40:"",
      letter_41:"e",letter_42:"w",letter_43:"e",letter_44:"",letter_45:"",
      letter_46:"",letter_47:"b",letter_48:"d",letter_49:"e",
      letter_50:"v",letter_51:"e",letter_52:"l",letter_53:"o",letter_54:"p",
      letter_55:"e",letter_56:"r",letter_57:"",letter_58:"",letter_59:"",
      letter_60:"",letter_61:"",letter_62:"",letter_63:"",letter_64:"",
      letter_65:"",letter_66:"",letter_67:"",letter_68:"",letter_69:"",
      lettermb_1:"H",lettermb_2:"e",lettermb_3:"l",lettermb_4:"l",lettermb_5:"o",
      lettermb_6:"!",lettermb_7:"M",lettermb_8:"",lettermb_9:"y",lettermb_10:"n",
      lettermb_11:"a",lettermb_12:"m",lettermb_13:"e",lettermb_14:"i",lettermb_15:"",
      lettermb_16:"",lettermb_17:"s",lettermb_18:"P",lettermb_19:"a",lettermb_20:"t",
      lettermb_21:"r",lettermb_22:"y",lettermb_23:"k",lettermb_24:",",lettermb_25:"I",
      lettermb_26:"'",lettermb_27:"",lettermb_28:"",lettermb_29:"",lettermb_30:"m",
      lettermb_31:"f",lettermb_32:"r",lettermb_33:"e",lettermb_34:"e",lettermb_35:"l",
      lettermb_36:"a",lettermb_37:"n",lettermb_38:"c",lettermb_39:"",lettermb_40:"",
      lettermb_41:"e",lettermb_42:"w",lettermb_43:"e",lettermb_44:"",lettermb_45:"",
      lettermb_46:"",lettermb_47:"b",lettermb_48:"d",lettermb_49:"e",
      lettermb_50:"v",lettermb_51:"e",lettermb_52:"l",lettermb_53:"o",lettermb_54:"p",
      lettermb_55:"e",lettermb_56:"r",lettermb_57:"",lettermb_58:"",lettermb_59:"",
      lettermb_60:"",lettermb_61:"",lettermb_62:"",lettermb_63:"",lettermb_64:"",
      lettermb_65:"",lettermb_66:"",lettermb_67:"",lettermb_68:"",lettermb_69:""

    },
    pl:{
      letter_1:"W",letter_2:"i",letter_3:"t",letter_4:"a",letter_5:"j",
      letter_6:"!",letter_7:"M",letter_8:"a",letter_9:"m",letter_10:"n",
      letter_11:"",letter_12:"",letter_13:"a",letter_14:"i",letter_15:"m",
      letter_16:"i",letter_17:"ę",letter_18:"P",letter_19:"a",letter_20:"t",
      letter_21:"r",letter_22:"y",letter_23:"k",letter_24:",",letter_25:"J",
      letter_26:"e",letter_27:"s",letter_28:"t",letter_29:"e",letter_30:"m",
      letter_31:"n",letter_32:"i",letter_33:"e",letter_34:"z",letter_35:"a",
      letter_36:"l",letter_37:"e",letter_38:"ż",letter_39:"n",letter_40:"y",
      letter_41:"m",letter_42:"t",letter_43:"w",letter_44:"ó",letter_45:"r",
      letter_46:"c",letter_47:"ą",letter_48:"s",letter_49:"t",letter_50:"r",
      letter_51:"o",letter_52:"",letter_53:"",letter_54:"",letter_55:"",
      letter_56:"n",letter_57:"i",letter_58:"n",letter_59:"t",letter_60:"e",
      letter_61:"r",letter_62:"n",letter_63:"e",letter_64:"t",letter_65:"o",
      letter_66:"w",letter_67:"y",letter_68:"c",letter_69:"h",
      lettermb_1:"W",lettermb_2:"i",lettermb_3:"t",lettermb_4:"a",lettermb_5:"j",
      lettermb_6:"!",lettermb_7:"M",lettermb_8:"a",lettermb_9:"m",lettermb_10:"n",
      lettermb_11:"",lettermb_12:"",lettermb_13:"a",lettermb_14:"i",lettermb_15:"m",
      lettermb_16:"i",lettermb_17:"ę",lettermb_18:"P",lettermb_19:"a",lettermb_20:"t",
      lettermb_21:"r",lettermb_22:"y",lettermb_23:"k",lettermb_24:",",lettermb_25:"J",
      lettermb_26:"e",lettermb_27:"s",lettermb_28:"t",lettermb_29:"e",lettermb_30:"m",
      lettermb_31:"n",lettermb_32:"i",lettermb_33:"e",lettermb_34:"z",lettermb_35:"a",
      lettermb_36:"l",lettermb_37:"e",lettermb_38:"ż",lettermb_39:"n",lettermb_40:"y",
      lettermb_41:"m",lettermb_42:"t",lettermb_43:"w",lettermb_44:"ó",lettermb_45:"r",
      lettermb_46:"c",lettermb_47:"ą",lettermb_48:"s",lettermb_49:"t",lettermb_50:"r",
      lettermb_51:"o",lettermb_52:"",lettermb_53:"",lettermb_54:"",lettermb_55:"",
      lettermb_56:"n",lettermb_57:"i",lettermb_58:"n",lettermb_59:"t",lettermb_60:"e",
      lettermb_61:"r",lettermb_62:"n",lettermb_63:"e",lettermb_64:"t",lettermb_65:"o",
      lettermb_66:"w",lettermb_67:"y",lettermb_68:"c",lettermb_69:"h"
    }
  };
  if(window.location.hash){
    if(window.location.hash==="#pl"){
      letter1.textContent=language.pl.letter_1;
      letter2.textContent=language.pl.letter_2;
      letter3.textContent=language.pl.letter_3;
      letter4.textContent=language.pl.letter_4;
      letter5.textContent=language.pl.letter_5;
      letter6.textContent=language.pl.letter_6;
      letter7.textContent=language.pl.letter_7;
      letter8.textContent=language.pl.letter_8;
      letter9.textContent=language.pl.letter_9;
      letter10.textContent=language.pl.letter_10;
      letter11.textContent=language.pl.letter_11;
      letter12.textContent=language.pl.letter_12;
      letter13.textContent=language.pl.letter_13;
      letter14.textContent=language.pl.letter_14;
      letter15.textContent=language.pl.letter_15;
      letter16.textContent=language.pl.letter_16;
      letter17.textContent=language.pl.letter_17;
      letter18.textContent=language.pl.letter_18;
      letter19.textContent=language.pl.letter_19;
      letter20.textContent=language.pl.letter_20;
      letter21.textContent=language.pl.letter_21;
      letter22.textContent=language.pl.letter_22;
      letter23.textContent=language.pl.letter_23;
      letter24.textContent=language.pl.letter_24;
      letter25.textContent=language.pl.letter_25;
      letter26.textContent=language.pl.letter_26;
      letter27.textContent=language.pl.letter_27;
      letter28.textContent=language.pl.letter_28;
      letter29.textContent=language.pl.letter_29;
      letter30.textContent=language.pl.letter_30;
      letter31.textContent=language.pl.letter_31;
      letter32.textContent=language.pl.letter_32;
      letter33.textContent=language.pl.letter_33;
      letter34.textContent=language.pl.letter_34;
      letter35.textContent=language.pl.letter_35;
      letter36.textContent=language.pl.letter_36;
      letter37.textContent=language.pl.letter_37;
      letter38.textContent=language.pl.letter_38;
      letter39.textContent=language.pl.letter_39;
      letter40.textContent=language.pl.letter_40;
      letter41.textContent=language.pl.letter_41;
      letter42.textContent=language.pl.letter_42;
      letter43.textContent=language.pl.letter_43;
      letter44.textContent=language.pl.letter_44;
      letter45.textContent=language.pl.letter_45;
      letter46.textContent=language.pl.letter_46;
      letter47.textContent=language.pl.letter_47;
      letter48.textContent=language.pl.letter_48;
      letter49.textContent=language.pl.letter_49;
      letter50.textContent=language.pl.letter_50;
      letter51.textContent=language.pl.letter_51;
      letter52.textContent=language.pl.letter_52;
      letter53.textContent=language.pl.letter_53;
      letter54.textContent=language.pl.letter_54;
      letter55.textContent=language.pl.letter_55;
      letter56.textContent=language.pl.letter_56;
      letter57.textContent=language.pl.letter_57;
      letter58.textContent=language.pl.letter_58;
      letter59.textContent=language.pl.letter_59;
      letter60.textContent=language.pl.letter_60;
      letter61.textContent=language.pl.letter_61;
      letter62.textContent=language.pl.letter_62;
      letter63.textContent=language.pl.letter_63;
      letter64.textContent=language.pl.letter_64;
      letter65.textContent=language.pl.letter_65;
      letter66.textContent=language.pl.letter_66;
      letter67.textContent=language.pl.letter_67;
      letter68.textContent=language.pl.letter_68;
      letter69.textContent=language.pl.letter_69;

      letter_mb1.textContent=language.pl.lettermb_1;
      letter_mb2.textContent=language.pl.lettermb_2;
      letter_mb3.textContent=language.pl.lettermb_3;
      letter_mb4.textContent=language.pl.lettermb_4;
      letter_mb5.textContent=language.pl.lettermb_5;
      letter_mb6.textContent=language.pl.lettermb_6;
      letter_mb7.textContent=language.pl.lettermb_7;
      letter_mb8.textContent=language.pl.lettermb_8;
      letter_mb9.textContent=language.pl.lettermb_9;
      letter_mb10.textContent=language.pl.lettermb_10;
      letter_mb11.textContent=language.pl.lettermb_11;
      letter_mb12.textContent=language.pl.lettermb_12;
      letter_mb13.textContent=language.pl.lettermb_13;
      letter_mb14.textContent=language.pl.lettermb_14;
      letter_mb15.textContent=language.pl.lettermb_15;
      letter_mb16.textContent=language.pl.lettermb_16;
      letter_mb17.textContent=language.pl.lettermb_17;
      letter_mb18.textContent=language.pl.lettermb_18;
      letter_mb19.textContent=language.pl.lettermb_19;
      letter_mb20.textContent=language.pl.lettermb_20;
      letter_mb21.textContent=language.pl.lettermb_21;
      letter_mb22.textContent=language.pl.lettermb_22;
      letter_mb23.textContent=language.pl.lettermb_23;
      letter_mb24.textContent=language.pl.lettermb_24;
      letter_mb25.textContent=language.pl.lettermb_25;
      letter_mb26.textContent=language.pl.lettermb_26;
      letter_mb27.textContent=language.pl.lettermb_27;
      letter_mb28.textContent=language.pl.lettermb_28;
      letter_mb29.textContent=language.pl.lettermb_29;
      letter_mb30.textContent=language.pl.lettermb_30;
      letter_mb31.textContent=language.pl.lettermb_31;
      letter_mb32.textContent=language.pl.lettermb_32;
      letter_mb33.textContent=language.pl.lettermb_33;
      letter_mb34.textContent=language.pl.lettermb_34;
      letter_mb35.textContent=language.pl.lettermb_35;
      letter_mb36.textContent=language.pl.lettermb_36;
      letter_mb37.textContent=language.pl.lettermb_37;
      letter_mb38.textContent=language.pl.lettermb_38;
      letter_mb39.textContent=language.pl.lettermb_39;
      letter_mb40.textContent=language.pl.lettermb_40;
      letter_mb41.textContent=language.pl.lettermb_41;
      letter_mb42.textContent=language.pl.lettermb_42;
      letter_mb43.textContent=language.pl.lettermb_43;
      letter_mb44.textContent=language.pl.lettermb_44;
      letter_mb45.textContent=language.pl.lettermb_45;
      letter_mb46.textContent=language.pl.lettermb_46;
      letter_mb47.textContent=language.pl.lettermb_47;
      letter_mb48.textContent=language.pl.lettermb_48;
      letter_mb49.textContent=language.pl.lettermb_49;
      letter_mb50.textContent=language.pl.lettermb_50;
      letter_mb51.textContent=language.pl.lettermb_51;
      letter_mb52.textContent=language.pl.lettermb_52;
      letter_mb53.textContent=language.pl.lettermb_53;
      letter_mb54.textContent=language.pl.lettermb_54;
      letter_mb55.textContent=language.pl.lettermb_55;
      letter_mb56.textContent=language.pl.lettermb_56;
      letter_mb57.textContent=language.pl.lettermb_57;
      letter_mb58.textContent=language.pl.lettermb_58;
      letter_mb59.textContent=language.pl.lettermb_59;
      letter_mb60.textContent=language.pl.lettermb_60;
      letter_mb61.textContent=language.pl.lettermb_61;
      letter_mb62.textContent=language.pl.lettermb_62;
      letter_mb63.textContent=language.pl.lettermb_63;
      letter_mb64.textContent=language.pl.lettermb_64;
      letter_mb65.textContent=language.pl.lettermb_65;
      letter_mb66.textContent=language.pl.lettermb_66;
      letter_mb67.textContent=language.pl.lettermb_67;
      letter_mb68.textContent=language.pl.lettermb_68;
      letter_mb69.textContent=language.pl.lettermb_69;
    }
  };
  for (i=0; i<=dataReload.length; i++){
    dataReload[i].onclick=function timeFunction() {
      setTimeout(function(){ history.go(0); }, 200);
    };
  };
}

change_language();
